#spring.application.name=sukemage

#spring.datasource.url=jdbc:postgresql://localhost:5432/sukemage
#spring.datasource.username=postgres
#spring.datasource.password=kumakichi7147

spring.application.name=webflowmanager

spring.datasource.url=jdbc:postgresql://ep-wispy-tooth-az5evkor-pooler.c-3.ap-southeast-1.aws.neon.tech/webflowmanager?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
