spring.application.name=sukemage

spring.datasource.url=jdbc:postgresql://localhost:5432/sukemage
spring.datasource.username=postgres
spring.datasource.password=kumakichi7147

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
